# Generated by Django 5.2.14 on 2026-05-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_serial', models.TextField(unique=True)),
                ('sensor_label', models.TextField(blank=True, default='')),
                ('sensor_type', models.TextField(default='DS18B20')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.TextField(unique=True)),
                ('rated_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rated_power_watts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_models',
                'indexes': [models.Index(fields=['model_name'], name='idx_product_models_model_name')],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.TextField(unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='sauna_data.productmodel')),
            ],
            options={
                'db_table': 'product_units',
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('test_run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField()),
                ('tester_name', models.TextField(blank=True, default='')),
                ('supply_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_amp_draw_start', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('run_duration_min', models.IntegerField(default=90)),
                ('target_temperature_f', models.DecimalField(decimal_places=2, default=150, max_digits=5)),
                ('test_location', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='sauna_data.productunit')),
            ],
            options={
                'db_table': 'test_runs',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reading_time', models.DateTimeField()),
                ('elapsed_time_min', models.IntegerField()),
                ('timer_remaining_min', models.IntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='sauna_data.sensor')),
                ('test_run', models.ForeignKey(db_column='test_run_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sauna_data.testrun')),
            ],
            options={
                'db_table': 'sensor_readings',
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('import_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('original_file_path', models.TextField(blank=True, default='')),
                ('archived_file_path', models.TextField(blank=True, default='')),
                ('status', models.TextField()),
                ('rows_imported', models.IntegerField(default=0)),
                ('sensors_detected', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('test_run', models.ForeignKey(blank=True, db_column='test_run_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='sauna_data.testrun')),
            ],
            options={
                'db_table': 'import_log',
            },
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['serial_number'], name='idx_product_units_serial'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['model'], name='idx_product_units_model_id'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['unit'], name='idx_test_runs_unit_id'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['test_date'], name='idx_test_runs_test_date'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['test_run'], name='idx_sensor_readings_test_run'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor'], name='idx_sensor_readings_sensor'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['reading_time'], name='idx_sensor_readings_time'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['test_run', 'reading_time'], name='idx_sensor_readings_run_time'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['file_name'], name='idx_import_log_file_name'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['status'], name='idx_import_log_status'),
        ),
    ]
