# Generated by Django 5.2.14 on 2026-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='supplier',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'GLOBAL'), ('ROYAL', 'ROYAL'), ('SMARTMAK', 'SMARTMAK')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_run_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='TestID'),
        ),
    ]
