# Generated by Django 5.2.14 on 2026-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna_data', '0002_productmodel_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')]),
        ),
    ]
