# Generated by Django 5.2.14 on 2026-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna_data', '0003_importlog_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='powerbox_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productunit',
            name='wattage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
