# Generated by Django 5.2.14 on 2026-05-25 20:56

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_POWERBOX_TYPES = ("Lee", "Luis", "Wang")


def seed_powerbox_types(apps, schema_editor):
    PowerBoxType = apps.get_model("sauna_data", "PowerBoxType")
    for name in DEFAULT_POWERBOX_TYPES:
        PowerBoxType.objects.get_or_create(name=name)


def migrate_legacy_powerbox_values(apps, schema_editor):
    ProductUnit = apps.get_model("sauna_data", "ProductUnit")
    PowerBoxType = apps.get_model("sauna_data", "PowerBoxType")
    for unit in ProductUnit.objects.exclude(powerbox_type_legacy=""):
        legacy = (unit.powerbox_type_legacy or "").strip()
        if not legacy:
            continue
        powerbox_type, _ = PowerBoxType.objects.get_or_create(name=legacy)
        unit.powerbox_type = powerbox_type
        unit.save(update_fields=["powerbox_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("sauna_data", "0004_productunit_powerbox_wattage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerBoxType",
            fields=[
                ("powerbox_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Power box type",
                "verbose_name_plural": "Power box types",
                "db_table": "powerbox_types",
            },
        ),
        migrations.RunPython(seed_powerbox_types, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="productunit",
            old_name="powerbox_type",
            new_name="powerbox_type_legacy",
        ),
        migrations.AddField(
            model_name="productunit",
            name="powerbox_type",
            field=models.ForeignKey(
                blank=True,
                db_column="powerbox_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="sauna_data.powerboxtype",
            ),
        ),
        migrations.RunPython(migrate_legacy_powerbox_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="productunit",
            name="powerbox_type_legacy",
        ),
    ]
